#!/bin/bash
set -e -E -C -u -o pipefail

. yadt-host-checkaccess

export SERVICE=${1:?no SERVICE specified}
readonly SERVICE_IGNOREFILE="${SERVICE:+$YADT_LOCK_DIR/ignore.$SERVICE}"

if [[ -f $SERVICE_IGNOREFILE ]]; then
    echo "service $SERVICE is ignored:" >&2
    cat $SERVICE_IGNOREFILE >&2
    exit $YADT_EXITCODE_SERVICE_IGNORED
fi
