#!/bin/bash
set -e -E -C -u -o pipefail

export YADT_SERVICE=${1:?no YADT_SERVICE specified}

if [ "7" -eq $RELEASEVER ]; then
    sudo systemctl status $YADT_SERVICE
else
    sudo service $YADT_SERVICE status
fi
