#!/bin/bash
set -e -E -C -u -o pipefail

. yadt-host-checkaccess

getopts r opts && {
    # remove option from $@
    shift $(( OPTIND - 1 ))
}

[[ -n $@ ]] && {
    sudo /usr/bin/yum upgrade -y $@
}

if [ "$opts" == "r" ]
    then
        sudo reboot
        sleep 42
        exit $YADT_EXITCODE_HOST_REBOOT_TIMEOUT
fi
