#!/bin/bash
set -e -E -C -u -o pipefail

export SERVICE=${1:?no SERVICE specified}
. yadt-service-checkaccess

if [ "7" -eq $RELEASEVER ]; then
    sudo systemctl stop $SERVICE
else
    sudo service $SERVICE stop
fi
