#!/bin/bash
set -e -E -C -u -o pipefail

export SERVICE=${1:?no SERVICE specified}
. yadt-service-checkaccess

eval $(yadt-service-init-type $SERVICE)
if [[ $YADT_INIT_TYPE == "sysv" ]]; then
    sudo service $SERVICE stop
elif [[ $YADT_INIT_TYPE == "upstart" ]]; then
    if sudo initctl status $SERVICE | grep -qv "stop/waiting"; then
        sudo initctl stop $SERVICE
    fi
elif [[ $YADT_INIT_TYPE == "systemd" ]]; then
    sudo systemctl stop $SERVICE >/dev/null
fi
