#!/bin/bash
set -e -E -C -u -o pipefail

. yadt-host-checkaccess

getopts r opts && {
    # remove option from $@
    shift $(( OPTIND - 1 ))
}

if [[ -n $@ ]]; then
    sudo /usr/bin/yum upgrade -y $@
fi

if [[ "$opts" == "r" ]]; then
    sudo $(whereis -b reboot | cut -d: -f2)
    sleep 42
    exit $YADT_EXITCODE_HOST_REBOOT_TIMEOUT
fi
