#!/bin/bash
set -e -E -C -u -o pipefail

export SERVICE=${1:?no SERVICE specified}
. yadt-service-checkaccess

is_already_starting() {
    # Only for SysV init, in case someone has broken init scripts.
    pgrep -f "(service $SERVICE start|.*sh /etc/rc..d/S..$SERVICE start)" > /dev/null
}

if ! is_already_starting; then
    echo "starting $SERVICE"
    if [[ $RELEASEVER == "7"* ]]
    then
        sudo systemctl start $SERVICE
    else
        sudo service $SERVICE start
    fi
    exit
fi

while is_already_starting; do
    echo "service $SERVICE is starting already, checking again in 2 seconds" >&2
    sleep 2
done
